databases:
  - name: q-economics-db
    databaseName: q_economics_db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: q-economics
    env: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: q-economics-db
          property: connectionString
      - key: PORT
        value: 8080
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
